### ISSUE TITLE
https://github.com/cake-contrib/Cake.MsDeploy/pull/31

### ISSUE THREAD

**Issue by sheriffjohn** [cake-contrib/Cake.Npm#74] opened 2018-03-09 08:28 UTC
**Description**
Cake Core has been updated but Cake.Npm still referencing older version.
My guess is that all Cake.XXX needs this fix. It has already been solved for Cake.MsDeploy

**Related**
https://github.com/cake-contrib/Cake.MsDeploy/pull/31

**Error**
Error: The assembly 'Cake.Npm, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by pascalberger** [comment] 2018-03-09 08:36
This is a duplicate of #70 

You can use the [0.13.0-beta0001](https://www.nuget.org/packages/Cake.Npm/0.13.0-beta0001) version which added support for Cake 0.26.0

**Closed by pascalberger** 2018-03-09 08:36 UTC
